const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Behaviors.Pin.Acts.PinByProperties
	];
};
self.C3_JsPropNameTable = [
	{Physics: 0},
	{ScrollTo: 0},
	{Car: 0},
	{Ground1_1: 0},
	{Keyboard: 0},
	{Sprite: 0},
	{Ground1_2: 0},
	{FrontChecker: 0},
	{RoofChecker: 0},
	{RearChecker: 0},
	{Anchor: 0},
	{FuelBar: 0},
	{FuelBackground: 0},
	{FuelCanister: 0},
	{LevelEnd: 0},
	{Audio: 0},
	{Ground2_2: 0},
	{Touch: 0},
	{LeftButton: 0},
	{RightButton: 0},
	{Restart: 0},
	{GroundL4A: 0},
	{GroundL4B: 0},
	{Ground2_1: 0},
	{Text: 0},
	{WinRestart: 0},
	{Mouse: 0},
	{RightTouchZone: 0},
	{LeftTouchZone: 0},
	{TimerText: 0},
	{WinL1: 0},
	{WinL2: 0},
	{WinL3: 0},
	{WinTotal: 0},
	{Level: 0},
	{Level1Copy: 0},
	{Level2A: 0},
	{Level2B: 0},
	{Level3A: 0},
	{Level3B: 0},
	{Level2A2: 0},
	{WinBackgroundv: 0},
	{TiledClouds: 0},
	{TiledClouds2: 0},
	{Bullet: 0},
	{BirdsSprite: 0},
	{Car0: 0},
	{WinScreen: 0},
	{TimeBG: 0},
	{Level2: 0},
	{Level3: 0},
	{WinL4: 0},
	{Level3B2: 0},
	{GroundL3A: 0},
	{GroundL3B: 0},
	{GroundL3BOLD: 0},
	{GroundL3AOLD: 0},
	{RaceStartScreen: 0},
	{Sprite2: 0},
	{MainMenuText: 0},
	{MuteBtn: 0},
	{MainMenuSign: 0},
	{Car3: 0},
	{Car2: 0},
	{RearChecker2: 0},
	{RearChecker3: 0},
	{RoofChecker2: 0},
	{RoofChecker3: 0},
	{FrontChecker2: 0},
	{FrontChecker3: 0},
	{Pin: 0},
	{Checkers: 0},
	{Ground: 0},
	{Cars: 0},
	{SelectedCar: 0},
	{canDrive: 0},
	{Fuel: 0},
	{TotalTime: 0},
	{CompletedTime: 0},
	{IsTransitioning: 0},
	{L1Time: 0},
	{L2Time: 0},
	{L3Time: 0},
	{L4Time: 0},
	{MusicChoice: 0},
	{NextStartMusic: 0},
	{NextL2Music: 0},
	{NextL3Music: 0},
	{NextL4Music: 0},
	{MenuReady: 0},
	{MusicMuted: 0}
];

self.InstanceType = {
	Car: class extends self.ISpriteInstance {},
	Ground1_1: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ground1_2: class extends self.ISpriteInstance {},
	FrontChecker: class extends self.ISpriteInstance {},
	RoofChecker: class extends self.ISpriteInstance {},
	RearChecker: class extends self.ISpriteInstance {},
	FuelBar: class extends self.ISpriteInstance {},
	FuelBackground: class extends self.ISpriteInstance {},
	FuelCanister: class extends self.ISpriteInstance {},
	LevelEnd: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Ground2_2: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LeftButton: class extends self.ISpriteInstance {},
	RightButton: class extends self.ISpriteInstance {},
	Restart: class extends self.ISpriteInstance {},
	GroundL4A: class extends self.ISpriteInstance {},
	GroundL4B: class extends self.ISpriteInstance {},
	Ground2_1: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	WinRestart: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	RightTouchZone: class extends self.ISpriteInstance {},
	LeftTouchZone: class extends self.ISpriteInstance {},
	TimerText: class extends self.ITextInstance {},
	WinL1: class extends self.ITextInstance {},
	WinL2: class extends self.ITextInstance {},
	WinL3: class extends self.ITextInstance {},
	WinTotal: class extends self.ITextInstance {},
	Level: class extends self.ISpriteInstance {},
	Level1Copy: class extends self.ISpriteInstance {},
	Level2A: class extends self.ISpriteInstance {},
	Level2B: class extends self.ISpriteInstance {},
	Level3A: class extends self.ISpriteInstance {},
	Level3B: class extends self.ISpriteInstance {},
	Level2A2: class extends self.ISpriteInstance {},
	WinBackgroundv: class extends self.ISpriteInstance {},
	TiledClouds: class extends self.ITiledBackgroundInstance {},
	TiledClouds2: class extends self.ITiledBackgroundInstance {},
	BirdsSprite: class extends self.ISpriteInstance {},
	Car0: class extends self.ISpriteInstance {},
	WinScreen: class extends self.ISpriteInstance {},
	TimeBG: class extends self.ISpriteInstance {},
	Level2: class extends self.ISpriteInstance {},
	Level3: class extends self.ISpriteInstance {},
	WinL4: class extends self.ITextInstance {},
	Level3B2: class extends self.ISpriteInstance {},
	GroundL3A: class extends self.ISpriteInstance {},
	GroundL3B: class extends self.ISpriteInstance {},
	GroundL3BOLD: class extends self.ISpriteInstance {},
	GroundL3AOLD: class extends self.ISpriteInstance {},
	RaceStartScreen: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MainMenuText: class extends self.ITextInstance {},
	MuteBtn: class extends self.ISpriteInstance {},
	MainMenuSign: class extends self.ISpriteInstance {},
	Car3: class extends self.ISpriteInstance {},
	Car2: class extends self.ISpriteInstance {},
	RearChecker2: class extends self.ISpriteInstance {},
	RearChecker3: class extends self.ISpriteInstance {},
	RoofChecker2: class extends self.ISpriteInstance {},
	RoofChecker3: class extends self.ISpriteInstance {},
	FrontChecker2: class extends self.ISpriteInstance {},
	FrontChecker3: class extends self.ISpriteInstance {},
	Checkers: class extends self.ISpriteInstance {},
	Ground: class extends self.ISpriteInstance {},
	Cars: class extends self.ISpriteInstance {}
}